name: soulbloom
description: A mental wellness focused card game.
publish_to: 'none'
version: 0.0.1+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  audioplayers: ^6.0.0
  go_router: ^14.0.0
  logging: ^1.2.0
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  yaml: ^3.1.3
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/data/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
